新增量子计算yml文件 and 修改数据库开发包'
oss-compass/compass-projects-information pull request #472
Opened 2023-06-12 02:21 UTC by QYFabc

2023-06-13 06:43 UTC, hncslwx requested changes

2023-06-13 06:43 UTC, hncslwx commented on collections/Quantum-Computing.yml
https://github.com/Qiskit/qiskit-aqua has archieved 项目已经存档并停止更新，请删除。

2023-06-13 06:43 UTC, hncslwx commented on collections/database-development-kit.yml
checked，ok

2023-06-14 01:36 UTC, eyehwan approved these changes
+1

2023-06-14 01:37 UTC, merged